### PR TITLE
DVX-48: Add support for search log access

### PR DESCRIPTION
**Pull request by Aryamanz29**
### Todos

- [x] monitor views of assets over some time span (this is part of the new search log)
- [x] monitor search queries for patterns (common / emerging) — also part of the new search log (via `cmd + k`)
- [x] add unit and integration tests.
- [x] add snippets to the developer portal docs.

#### 1.  Without time range

```py
from pyatlan.model.search_log import SearchLogRequest
from pyatlan.client.atlan import AtlanClient

client = AtlanClient()

request = SearchLogRequest.by_guid(
    guid="<asset-guid>", user_size=2
)
response = client.search_log.search(request)

print(f"Total Assets Views : {response.total_views}")

for user in response.unique_users:
    print(
        f"Username : {user.name}, View count: {user.view_count}, Last view timestamp : {user.view_timestamp}"
    )
```

#### Output:
```bash
Total Assets Views : 39
Username : aryaman.bhushan, View count: 37, Last view timestamp : 2023-12-05 11:27:56.977000+00:00
Username : chris, View count: 2, Last view timestamp : 2023-12-05 09:52:46.723000+00:00
```

#### 2. With time range

```py
client = AtlanClient()

# 4 hrs ago
request = SearchLogRequest.by_guid(
    guid="<asset-guid>",
    user_size=2,
    start_time=1701766262000,
    end_time=1701780919766,
)

response = client.search_log.search(request)
print(f"Total Assest Views : {response.total_views}")

for user in response.unique_users:
    print(
        f"Username : {user.name}, View count: {user.view_count}, Last view timestamp : {user.view_timestamp}"
    )
```

```bash
Total Assest Views : 13
Username : aryaman.bhushan, View count: 12, Last view timestamp : 2023-12-05 11:27:56.977000+00:00
Username : chris, View count: 1, Last view timestamp : 2023-12-05 09:52:46.723000+00:00
```

#### 3. Retrieve recent search log

```py
client = AtlanClient()
request = SearchLogRequest.get_recent_search(usernames=["aryaman.bhushan"], size=5)
response = client.search_log.search(request)

print(f"Total search count: {response.total_count}")
for asset_log in response:
    print(asset_log.dict())
```

```bash
Total search count: 81
{'log_host': 'devx.atlan.com', 'log_ipaddress': '<ip_address>', 'log_user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15...', 'log_username': 'aryaman.bhushan', 'log_guid': '<asset_guid>', 'log_qualified_name': '<asset_qualified_name>', 'log_type_name': 'Table', 'log_timestamp': datetime.datetime(2023, 12, 6, 8, 26, 59, 986000, tzinfo=datetime.timezone.utc)}
...
...
```

### CODE REVIEW

**Comment by cmgrote** [comment]
Looking good to me — just curious if the response object(s) are capturing all output that comes back (full response payload)?

**Comment by Aryamanz29** [comment]
> Looking good to me — just curious if the response object(s) are capturing all output that comes back (full response payload)?

Nope, I'm only capturing `aggregations{}`, `approximateCount`, and excluding `"searchParameters": {"dsl": "{}", "querystring": {}}` (since it's the same as the request payload)

```json
    "aggregations": {
        "topVisitors": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "aryaman.bhushan",
                    "doc_count": 40,
                    "viewsSum": {
                        "value": 40.0
                    }
                },
                {
                    "key": "chris",
                    "doc_count": 2,
                    "viewsSum": {
                        "value": 2.0
                    }
                }
            ]
        },
        "totalDistinctUsers": {
            "value": 2
        },
        "uniqueUsers": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "aryaman.bhushan",
                    "doc_count": 40,
                    "latest_timestamp": {
                        "value": 1701786209995
                    }
                },
                {
                    "key": "chris",
                    "doc_count": 2,
                    "latest_timestamp": {
                        "value": 1701769966723
                    }
                }
            ]
        }
    },
    "approximateCount": 42
```

**Comment by Aryamanz29** [comment]
> thinking it would be good to have the user_size parameter also be optional (e.g. "just show me everyone who's viewed this asset in the last 90 days"), or is it required in the request? (if required in the request we might still want to just default it to some value like 10 if not passed to the method)

It is optional, and I have set the default value to `20`, similar to the frontend UI.

> also I would probably change the named parameter from user_size to max_users

Sure, that would be nice, I'll update that!

**Comment by cmgrote** [comment]
> excluding "searchParameters": {"dsl": "{}", "querystring": {}} (since it's the same as the request payload)

But we are capturing the original request, so we can use that to simplify paging (just iterating over the results object), right? 🤞

**Review by cmgrote — COMMENTED** [review]
Did you get paging to work in the end, or is it still not working?

If still not working, @ErnestoLoma can you have a quick review and see if you can spot anything obvious?

**Comment by Aryamanz29** [comment]
> Did you get paging to work in the end, or is it still not working?

Yes, it works for retrieving detailed search log entries.

**Review by cmgrote — APPROVED** [review]

**Pull request merged**
