### PR TITLE
DVX-51: Add JSON formatter to the logger

### PR DESCRIPTION
**Pull request by Aryamanz29**
### Before

```
2023-11-22 15:19:32,329 - pyatlan.client.atlan - DEBUG - {'totalRecord': 5, 'filterRecord': 1, 'records': [{'alias': 'Admins', 'attributes': {'alias': ['Admins'], 'createdAt': ['1691010302538'], 'createdBy': ['<hidden>'], 'isDefault': ['true'], 'updatedAt': ['1691016077625'], 'updatedBy': ['chris']}, 'id': '<hidden>', 'name': 'admins', 'path': '/admins', 'personas': [{'id': '<hidden>', 'name': 'Business Definitions', 'displayName': 'Business Definitions', 'qualifiedName': '<hidden>'}, {'id': '<hidden>', 'name': 'Data Assets', 'displayName': 'Data Assets', 'qualifiedName': '<hidden>'}], 'purposes': [{'guid': '<hidden>', 'name': 'Known Issues', 'qualifiedName': '<hidden>'}], 'userCount': 8}]}
```

### After

```
2023-11-22 15:16:47,514 - pyatlan.client.atlan - DEBUG - {"totalRecord": 5, "filterRecord": 1, "records": [{"alias": "Admins", "attributes": {"alias": ["Admins"], "createdAt": ["1691010302538"], "createdBy": ["<>"], "isDefault": ["true"], "updatedAt": ["1691016077625"], "updatedBy": ["chris"]}, "id": "<>", "name": "admins", "path": "/admins", "personas": [{"id": "<hidden>", "name": "Business Definitions", "displayName": "Business Definitions", "qualifiedName": "<hidden>"}, {"id": "<hidden>", "name": "Data Assets", "displayName": "Data Assets", "qualifiedName": "<hidden>"}], "purposes": [{"guid": "<hidden>", "name": "Known Issues", "qualifiedName": "<hidden>"}], "userCount": 8}]}
```

💡 There is one well-maintained package I found while working on this: [python-json-logger](https://github.com/madzak/python-json-logger) for some advanced customization with JSON formatting using Python logger.

### CODE REVIEW

**Review by ErnestoLoma — COMMENTED** [review]
I was anticipating the entire log entry to be JSON not just the message so something like:
`{"asctime": "2023-11-22 15:16:47,514", "name": "pyatlan.client.atlan", "levelname": "DEBUG", "message": {"totalRecord": 5, "filterRecord": 1, "records": [{"alias": "Admins", "attributes": {"alias": ["Admins"], "createdAt": ["1691010302538"], "createdBy": ["<>"], "isDefault": ["true"], "updatedAt": ["1691016077625"], "updatedBy": ["chris"]}, "id": "<>", "name": "admins", "path": "/admins", "personas": [{"id": "<hidden>", "name": "Business Definitions", "displayName": "Business Definitions", "qualifiedName": "<hidden>"}, {"id": "<hidden>", "name": "Data Assets", "displayName": "Data Assets", "qualifiedName": "<hidden>"}], "purposes": [{"guid": "<hidden>", "name": "Known Issues", "qualifiedName": "<hidden>"}], "userCount": 8}]}}`

**Review by ErnestoLoma — CHANGES_REQUESTED** [review]
I was anticipating the entire log entry to be JSON not just the message so something like:
`{"asctime": "2023-11-22 15:16:47,514", "name": "pyatlan.client.atlan", "levelname": "DEBUG", "message": {"totalRecord": 5, "filterRecord": 1, "records": [{"alias": "Admins", "attributes": {"alias": ["Admins"], "createdAt": ["1691010302538"], "createdBy": ["<>"], "isDefault": ["true"], "updatedAt": ["1691016077625"], "updatedBy": ["chris"]}, "id": "<>", "name": "admins", "path": "/admins", "personas": [{"id": "<hidden>", "name": "Business Definitions", "displayName": "Business Definitions", "qualifiedName": "<hidden>"}, {"id": "<hidden>", "name": "Data Assets", "displayName": "Data Assets", "qualifiedName": "<hidden>"}], "purposes": [{"guid": "<hidden>", "name": "Known Issues", "qualifiedName": "<hidden>"}], "userCount": 8}]}}`

**Comment by Aryamanz29** [comment]
> I was anticipating the entire log entry to be JSON not just the message so something like: `{"asctime": "2023-11-22 15:16:47,514", "name": "pyatlan.client.atlan", "levelname": "DEBUG", "message": {"totalRecord": 5, "filterRecord": 1, "records": [{"alias": "Admins", "attributes": {"alias": ["Admins"], "createdAt": ["1691010302538"], "createdBy": ["<>"], "isDefault": ["true"], "updatedAt": ["1691016077625"], "updatedBy": ["chris"]}, "id": "<>", "name": "admins", "path": "/admins", "personas": [{"id": "<hidden>", "name": "Business Definitions", "displayName": "Business Definitions", "qualifiedName": "<hidden>"}, {"id": "<hidden>", "name": "Data Assets", "displayName": "Data Assets", "qualifiedName": "<hidden>"}], "purposes": [{"guid": "<hidden>", "name": "Known Issues", "qualifiedName": "<hidden>"}], "userCount": 8}]}}`

Thanks for clarifying, @ErnestoLoma! I've updated the method to generate the entire log entry in JSON format.

**Review by ErnestoLoma — CHANGES_REQUESTED** [review]
I think we should have both the simple and jsonFormatter as well as a fileHandler and jsonHandler.  The jsonHandler should write to /tmp/pyatlan.json.

**Review by ErnestoLoma — APPROVED** [review]

**Pull request merged**
